name: Pull Request Checks

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    name: Run Build in Pull Request Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build Next.js app
        run: npm run build

      - name: Check build status
        run: |
          echo "✅ Next.js build completed successfully!"
          echo "The application can be built without errors."
